interface PolizaOrdenada {
    FECHA_RENOVACION: string; // fec_fin_poliza
    GESTOR: string; // 0
    ID_CORREDOR: string; // id_intermediario
    CORREDOR: string; // des_intermediario
    ID_CONTRATANTE: string; // id_contratante
    CONTRATANTE: string; // des_contratante
    SEGMENTO: string; // des_segmento_empresa_contratante
    SUBSEGMENTO: string; // 0
    ID_PRODUCTO: string; // id_producto
    PRODUCTO: string; // des_producto
    ID_PLAN: string; // id_version_plan
    ID_REVISION: string; // id_version_plan
    PLAN_REVISION: string; // des_version_plan
    POLIZA: string; // num_poliza
    IDEPOL: string; // id_poliza
    NUMTRAMITE: string; // num_tramite_renovacion
    ESTADO: string; // 0
    RESPONSABLE: string; // 0
    STSRENOVSIG: string; // 0
    INICIO_VIGENCIA: string; // fec_inicio_poliza
    FIN_VIGENCIA: string; // fec_fin_poliza
    GIRO: string; // giro
    CLASIFICACION: string; // des_giro_clasificacion_direccion_riesgo
    RER_MINIMO: string; // des_nota_inspeccion_rer_direccion_riesgo
    TIPOGIRO: string; // tip_giro_direccion_riesgo
    ID_OFICINA: string; // 0
    ID_ESTADO: string; // id_estado_poliza
    ID_TIPO_PRODUCCION: string; // 0
    PORC_COASEG_ACEP: string; // 0
    PORC_COASEGCED: string; // 0
    TIPO_REASEGURO: string; // 0
    POLIZA_FACULTATIVA: string; // ind_facultativo_poliza
    IND_FRONTING: string; // ind_fronting_poliza
    PRIMA_EMITIDA: string; // mnt_prima_emitida_usd
    PRIMA_COASEGURO_ACEPTADO: string; // 0
    PRIMA_COASEGURO_CEDIDO: string; // 0
    PRIMA_NP: string; // mnt_prima_np_usd
    PRIMA_TOTAL_REASEGURADA: string; // prima_total_reasegurada
    PRIMA_RETENIDA: string; // mnt_prima_retenida
    COMISION_AGENTE: string; // mnt_comision_np_usd
    TOTAL_DSCTO_REASEGURO: string; // 0
    SINIESTRO_100: string; // mnt_siniestro_reserva_usd
    SINIESTRO_COASEGURO_ACEP: string; // 0
    SINIESTRO_COASEGURO_CED: string; // 0
    SINIESTRO_NP: string; // 0
    SINIESTRO_TOTAL_REASEGURADO: string; // 0
    SINIESTRO_RETENIDO: string; // 0
    PRIMA_DEVENGADA: string; // prima_devengada
    PRIMA_COASEGURO_ACEP_DEV: string; // 0
    PRIMA_COASEGURO_CED_DEV: string; // 0
    PRIMA_NP_DEV: string; // mnt_prima_np_usd
    PRIMA_TOTAL_REASEGURADA_DEV: string; // prima_total_reasegurada
    PRIMA_RETENIDA_DEV: string; // mnt_prima_retenida
    COMISION_AGENTE_DEV: string; // mnt_comision_np_usd
    TOTAL_COMISION_REASEGURO_DEV: string; // 0
    RESULTADO_TECNICO: string; // 0
    RESULTADO_TECNICO_PORC: string; // 0
    DEC_EXIST: string; // N
    MTOVALORDEC: string; // mnt_valor_declarado_direccion_riesgo
    SUMASEG: string; // mnt_suma_asegurada_usd
    [key: string]: string;
}
